global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'api1:80'
          - 'api2:80'
          - 'prometheus:9090'
          - 'idonotexists:564'
