{
 "title": "APIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Req/s by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rinha_de_backend_requests_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Req/s by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rinha_de_backend_requests_total{host=\"api\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(rinha_de_backend_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(rinha_de_backend_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(rinha_de_backend_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(rinha_de_backend_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Goroutines by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"api1:80\"}",
     "legendFormat": "api1"
    },
    {
     "expr": "go_goroutines{instance=\"api2:80\"}",
     "legendFormat": "api2"
    }
   ]
  }
 ]
}